# Generated by Django 3.0.5 on 2020-04-30 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='name',
            new_name='user',
        ),
    ]
